### PR TITLE
Update OpenAi.list

### PR DESCRIPTION
**Pull request by Geniucker**
feat: add 2 domains for OpenAI

### CODE REVIEW

**Comment by 8MiYile** [comment]
@Geniucker 不止一个.list文件 还有一个.yml的 也要跟着改

**Comment by Geniucker** [comment]
👌

**Comment by fxzxmicah** [comment]
应该排下序

**Comment by Geniucker** [comment]
> 应该排下序

finished

**Comment by JamesWDGu** [comment]
Hi @acl4ssr-sub , I hope to merge it soon, this is very useful to me, thanks @Geniucker 's PR!

**Comment by JamesWDGu** [comment]
There are also two domain names oaistatic.com and oaiusercontent.com for files uploaded by DALL·E. It would be better if you could add them to this PR. @Geniucker

**Comment by Geniucker** [comment]
> There are also two domain names oaistatic.com and oaiusercontent.com for files uploaded by DALL·E. It would be better if you could add them to this PR. @Geniucker

These 2 domains are what I added

**Comment by 8MiYile** [comment]
@acl4ssr-sub 3天了还没更新（）

**Comment by maqic** [comment]
快更新配置吧🥺

**Comment by devyujie** [comment]
+1

**Pull request merged**
